"""empty message

Revision ID: 3070fc19220b
Revises: 
Create Date: 2022-03-14 14:16:32.302398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3070fc19220b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=500), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('activity_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('activities_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=500), nullable=False),
    sa.Column('activity_description', sa.String(length=500), nullable=False),
    sa.Column('activity_todo_list', sa.String(length=500), nullable=False),
    sa.Column('activity_conditions_temp', sa.Integer(), nullable=False),
    sa.Column('activity_conditions_1', sa.String(length=10), nullable=True),
    sa.Column('activity_conditions_2', sa.String(length=10), nullable=True),
    sa.Column('activity_conditions_3', sa.String(length=10), nullable=True),
    sa.Column('activity_conditions_4', sa.String(length=10), nullable=True),
    sa.Column('activity_conditions_5', sa.String(length=10), nullable=True),
    sa.Column('activity_conditions_6', sa.String(length=10), nullable=True),
    sa.Column('activity_conditions_7', sa.String(length=10), nullable=True),
    sa.Column('activity_conditions_8', sa.String(length=10), nullable=True),
    sa.Column('activity_conditions_9', sa.String(length=10), nullable=True),
    sa.Column('activity_calories', sa.String(length=100), nullable=True),
    sa.Column('activity_favourite', sa.String(length=10), nullable=True),
    sa.Column('activity_level1', sa.String(length=10), nullable=True),
    sa.Column('activity_level2', sa.String(length=10), nullable=True),
    sa.Column('activity_level3', sa.String(length=10), nullable=True),
    sa.Column('activity_timestamp', sa.DateTime(), nullable=True),
    sa.Column('activity_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_table_activity_timestamp'), 'activities_table', ['activity_timestamp'], unique=False)
    op.create_table('weather_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_date', sa.String(length=100), nullable=True),
    sa.Column('weather_day', sa.Integer(), nullable=True),
    sa.Column('weather_location', sa.String(length=100), nullable=True),
    sa.Column('weather_day_name', sa.String(length=100), nullable=True),
    sa.Column('weather_temperature', sa.Integer(), nullable=True),
    sa.Column('weather_wind', sa.Integer(), nullable=True),
    sa.Column('weather_cloud', sa.Integer(), nullable=True),
    sa.Column('weather_description', sa.String(length=500), nullable=True),
    sa.Column('weather_icon', sa.String(length=100), nullable=True),
    sa.Column('weather_main', sa.String(length=300), nullable=True),
    sa.Column('weather_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weather_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_table_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_date', sa.String(length=100), nullable=True),
    sa.Column('weather_day', sa.Integer(), nullable=True),
    sa.Column('weather_location', sa.String(length=100), nullable=True),
    sa.Column('weather_day_name', sa.String(length=100), nullable=True),
    sa.Column('weather_temperature', sa.Integer(), nullable=True),
    sa.Column('weather_wind', sa.Integer(), nullable=True),
    sa.Column('weather_cloud', sa.Integer(), nullable=True),
    sa.Column('weather_description', sa.String(length=500), nullable=True),
    sa.Column('weather_icon', sa.String(length=100), nullable=True),
    sa.Column('weather_user_id', sa.Integer(), nullable=True),
    sa.Column('weather_main', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['weather_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icons_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon_name', sa.String(length=10), nullable=True),
    sa.Column('icon_value', sa.String(length=10), nullable=True),
    sa.Column('icon_link', sa.String(length=100), nullable=True),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['weather_table.weather_icon'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icons_table')
    op.drop_table('weather_table_history')
    op.drop_table('weather_table')
    op.drop_index(op.f('ix_activities_table_activity_timestamp'), table_name='activities_table')
    op.drop_table('activities_table')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
