"""create user table

Revision ID: 3b42cd8b32e2
Revises: 
Create Date: 2022-03-06 12:28:41.021943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b42cd8b32e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('activity_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activite_name', sa.String(length=100), nullable=False),
    sa.Column('activite_description', sa.String(length=200), nullable=False),
    sa.Column('activite_todo_list', sa.String(length=200), nullable=False),
    sa.Column('activite_conditions', sa.Integer(), nullable=False),
    sa.Column('activite_calories', sa.String(length=100), nullable=True),
    sa.Column('activite_favorite', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_description_timestamp'), 'activity_description', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_description_timestamp'), table_name='activity_description')
    op.drop_table('activity_description')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
