"""empty message

Revision ID: f06355fe4915
Revises: 
Create Date: 2022-03-24 12:31:33.681723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06355fe4915'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chosen_activities_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chosen_activity_name', sa.String(length=500), nullable=False),
    sa.Column('chosen_status', sa.Boolean(), nullable=True),
    sa.Column('chosen_activity_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chosen_activities_table_chosen_activity_timestamp'), 'chosen_activities_table', ['chosen_activity_timestamp'], unique=False)
    op.create_table('chosen_activities_table_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chosen_activity_name', sa.String(length=500), nullable=False),
    sa.Column('chosen_status', sa.Boolean(), nullable=True),
    sa.Column('chosen_activity_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chosen_activities_table_history_chosen_activity_timestamp'), 'chosen_activities_table_history', ['chosen_activity_timestamp'], unique=False)
    op.create_table('city_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=500), nullable=False),
    sa.Column('city_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_table_city_timestamp'), 'city_table', ['city_timestamp'], unique=False)
    op.create_table('icons_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon_name', sa.String(length=10), nullable=True),
    sa.Column('icon_value', sa.String(length=10), nullable=True),
    sa.Column('icon_link', sa.String(length=100), nullable=True),
    sa.Column('icon_value2', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_user', sa.String(length=100), nullable=True),
    sa.Column('image_user_id', sa.String(length=100), nullable=True),
    sa.Column('image_date', sa.DateTime(), nullable=True),
    sa.Column('image_name', sa.String(length=100), nullable=True),
    sa.Column('image_description', sa.String(length=500), nullable=True),
    sa.Column('image_link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=500), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('activity_level1', sa.Boolean(), nullable=True),
    sa.Column('activity_level2', sa.Boolean(), nullable=True),
    sa.Column('activity_level3', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('weather_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_date', sa.DateTime(), nullable=True),
    sa.Column('weather_day', sa.String(length=100), nullable=True),
    sa.Column('weather_location', sa.String(length=100), nullable=True),
    sa.Column('weather_day_name', sa.String(length=100), nullable=True),
    sa.Column('weather_temperature', sa.Integer(), nullable=True),
    sa.Column('weather_wind', sa.Integer(), nullable=True),
    sa.Column('weather_cloud', sa.Integer(), nullable=True),
    sa.Column('weather_description', sa.String(length=500), nullable=True),
    sa.Column('weather_icon', sa.String(length=100), nullable=True),
    sa.Column('weather_main', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_table_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_date', sa.DateTime(), nullable=True),
    sa.Column('weather_day', sa.String(length=100), nullable=True),
    sa.Column('weather_location', sa.String(length=100), nullable=True),
    sa.Column('weather_day_name', sa.String(length=100), nullable=True),
    sa.Column('weather_temperature', sa.Integer(), nullable=True),
    sa.Column('weather_wind', sa.Integer(), nullable=True),
    sa.Column('weather_cloud', sa.Integer(), nullable=True),
    sa.Column('weather_description', sa.String(length=500), nullable=True),
    sa.Column('weather_icon', sa.String(length=100), nullable=True),
    sa.Column('weather_main', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=500), nullable=False),
    sa.Column('activity_description', sa.String(length=500), nullable=False),
    sa.Column('activity_todo_list', sa.String(length=500), nullable=False),
    sa.Column('activity_conditions_temp', sa.Integer(), nullable=False),
    sa.Column('activity_conditions_1', sa.Boolean(), nullable=True),
    sa.Column('activity_conditions_2', sa.Boolean(), nullable=True),
    sa.Column('activity_conditions_3', sa.Boolean(), nullable=True),
    sa.Column('activity_conditions_4', sa.Boolean(), nullable=True),
    sa.Column('activity_conditions_5', sa.Boolean(), nullable=True),
    sa.Column('activity_conditions_6', sa.Boolean(), nullable=True),
    sa.Column('activity_conditions_7', sa.Boolean(), nullable=True),
    sa.Column('activity_conditions_8', sa.Boolean(), nullable=True),
    sa.Column('activity_conditions_9', sa.Boolean(), nullable=True),
    sa.Column('activity_calories', sa.String(length=100), nullable=True),
    sa.Column('activity_favourite', sa.Boolean(), nullable=True),
    sa.Column('activity_level1', sa.Boolean(), nullable=True),
    sa.Column('activity_level2', sa.Boolean(), nullable=True),
    sa.Column('activity_level3', sa.Boolean(), nullable=True),
    sa.Column('activity_timestamp', sa.DateTime(), nullable=True),
    sa.Column('activity_user_id', sa.Integer(), nullable=True),
    sa.Column('activity_conditions_1_icon', sa.String(length=100), nullable=True),
    sa.Column('activity_conditions_2_icon', sa.String(length=100), nullable=True),
    sa.Column('activity_conditions_3_icon', sa.String(length=100), nullable=True),
    sa.Column('activity_conditions_4_icon', sa.String(length=100), nullable=True),
    sa.Column('activity_conditions_5_icon', sa.String(length=100), nullable=True),
    sa.Column('activity_conditions_6_icon', sa.String(length=100), nullable=True),
    sa.Column('activity_conditions_7_icon', sa.String(length=100), nullable=True),
    sa.Column('activity_conditions_8_icon', sa.String(length=100), nullable=True),
    sa.Column('activity_conditions_9_icon', sa.String(length=100), nullable=True),
    sa.Column('chosen_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['activity_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_table_activity_timestamp'), 'activities_table', ['activity_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_table_activity_timestamp'), table_name='activities_table')
    op.drop_table('activities_table')
    op.drop_table('weather_table_history')
    op.drop_table('weather_table')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('image_table')
    op.drop_table('icons_table')
    op.drop_index(op.f('ix_city_table_city_timestamp'), table_name='city_table')
    op.drop_table('city_table')
    op.drop_index(op.f('ix_chosen_activities_table_history_chosen_activity_timestamp'), table_name='chosen_activities_table_history')
    op.drop_table('chosen_activities_table_history')
    op.drop_index(op.f('ix_chosen_activities_table_chosen_activity_timestamp'), table_name='chosen_activities_table')
    op.drop_table('chosen_activities_table')
    # ### end Alembic commands ###
